# Generated by Django 6.1.1 on 2026-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackly', '0003_alter_monitor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.URLField(),
        ),
    ]
