# Generated by Django 6.1.1 on 2026-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackly', '0002_monitor_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
