# Generated by Django 6.1.1 on 2026-10-08 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackly', '0004_alter_monitor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
